# Generated by Django 4.2 on 2025-11-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgiiee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='forma_recinto',
            field=models.CharField(choices=[('triangulo', 'Triángulo'), ('cuadrado', 'Cuadrado'), ('rectangulo', 'Rectángulo'), ('circulo', 'Círculo'), ('hexagono', 'Hexágono'), ('octagono', 'Octágono')], default='cuadrado', max_length=20),
        ),
    ]
