# Generated by Django 4.2 on 2025-11-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgiiee', '0002_evento_forma_recinto'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='pos_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asiento',
            name='pos_y',
            field=models.FloatField(default=0),
        ),
    ]
