# Generated by Django 4.2 on 2025-12-01 03:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgiiee', '0003_asiento_pos_x_asiento_pos_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='asiento',
            name='zona',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('apartado', 'Apartado'), ('vendido', 'Vendido')], default='disponible', max_length=15),
        ),
    ]
