# Generated by Django 4.2 on 2025-12-02 01:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgiiee', '0004_asiento_precio_asiento_zona_evento_precio_base_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='precio_base',
            new_name='precio_normal',
        ),
        migrations.AddField(
            model_name='evento',
            name='precio_avanzado',
            field=models.DecimalField(decimal_places=2, default=Decimal('180.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='evento',
            name='precio_vip',
            field=models.DecimalField(decimal_places=2, default=Decimal('300.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='evento',
            name='forma_recinto',
            field=models.CharField(choices=[('triangulo', 'Triángulo'), ('cuadrado', 'Cuadrado'), ('rectangulo', 'Rectángulo'), ('circulo', 'Circulo'), ('hexagono', 'Hexágono'), ('octagono', 'Octágono')], default='cuadrado', max_length=20),
        ),
    ]
