# Generated by Django 4.2 on 2025-12-02 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sgiiee', '0005_rename_precio_base_evento_precio_normal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcarrito',
            options={'ordering': ['-agregado_en'], 'verbose_name': 'Item de Carrito', 'verbose_name_plural': 'Items de Carrito'},
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='sgiiee.asiento'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to=settings.AUTH_USER_MODEL),
        ),
    ]
